CREATE DATABASE IF NOT EXISTS irzserver4 CHARACTER SET = utf8;
USE irzserver4;
CREATE TABLE IF NOT EXISTS devices (imei BIGINT NOT NULL, channel TINYINT NOT NULL DEFAULT -1, state TINYINT NOT NULL, IP CHAR(16), port CHAR(6), description VARCHAR(100), password CHAR(20), delivery BOOLEAN, interface TINYTEXT, encapsulation CHAR(10), serveraddress VARCHAR(25), callback BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY (imei, channel));
ALTER TABLE devices ADD INDEX dev_IP_ind (IP);
ALTER TABLE devices ADD INDEX dev_imei_ind (imei);
USE irzserver4;
CREATE TABLE IF NOT EXISTS deviceHistory (id BIGINT AUTO_INCREMENT PRIMARY KEY,date BIGINT UNSIGNED, action TINYINT UNSIGNED NOT NULL, imei BIGINT NOT NULL,address TINYTEXT, phone1 CHAR(20), phone2 CHAR(20),timetable CHAR(15),otap CHAR(10),firmware TINYINT UNSIGNED, revision TINYINT UNSIGNED, hardware CHAR(5), build CHAR(10), devtype CHAR(10), FOREIGN KEY (imei) REFERENCES devices(imei));
ALTER TABLE deviceHistory ADD INDEX hist_date_ind (date);
ALTER TABLE deviceHistory ADD INDEX hist_imei_ind (imei);
ALTER TABLE deviceHistory ADD INDEX hist_imei_date_ind (imei, date);
USE irzserver4;
CREATE TABLE IF NOT EXISTS sessions (id BIGINT PRIMARY KEY AUTO_INCREMENT, conndate BIGINT UNSIGNED, csq TINYINT UNSIGNED, balance FLOAT, sim TINYINT(1), disdate BIGINT UNSIGNED, traffic MEDIUMINT UNSIGNED, trfin MEDIUMINT UNSIGNED DEFAULT 0, trfout MEDIUMINT UNSIGNED DEFAULT 0, imei BIGINT NOT NULL, channel TINYINT NOT NULL DEFAULT -1, FOREIGN KEY (imei) REFERENCES devices(imei));
ALTER TABLE sessions ADD INDEX ses_date_ind (conndate);
ALTER TABLE sessions ADD INDEX ses_imei_ind (imei);
ALTER TABLE sessions ADD INDEX ses_imei_date_ind (imei, conndate);
USE irzserver4;
CREATE TABLE IF NOT EXISTS users (name CHAR(32) NOT NULL, password CHAR(40) NOT NULL, access TINYINT UNSIGNED NOT NULL,enc_com BOOLEAN DEFAULT TRUE,mod_modem_set BOOLEAN DEFAULT TRUE,update_set BOOLEAN DEFAULT TRUE,add_delete_modem BOOLEAN DEFAULT TRUE,mod_modem_des BOOLEAN DEFAULT TRUE,firm_upgrade BOOLEAN DEFAULT TRUE, mod_warn_set BOOLEAN DEFAULT TRUE,PRIMARY KEY(name));
USE irzserver4;
CREATE TABLE IF NOT EXISTS commands_list (id int(30) PRIMARY KEY NOT NULL,command varbinary(300) NOT NULL,comGroup int(11) DEFAULT NULL);
USE irzserver4;
CREATE TABLE IF NOT EXISTS commands (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,imei bigint(20) NOT NULL,queued bigint(20) unsigned DEFAULT NULL, com_date bigint(20) unsigned DEFAULT NULL, attempts tinyint DEFAULT '0', answer varbinary(300) DEFAULT NULL, ans_date bigint(20) unsigned DEFAULT NULL, command TINYTEXT, error tinyint(1) DEFAULT '0', interrupt tinyint(1) DEFAULT '0', command_id int(11), encapsulation char(10) DEFAULT NULL, FOREIGN KEY (command_id) REFERENCES commands_list(id));
ALTER TABLE commands ADD INDEX com_date_ind (com_date);
ALTER TABLE commands ADD INDEX ans_date_ind (ans_date);
ALTER TABLE commands ADD INDEX que_date_ind (queued);
ALTER TABLE commands ADD INDEX com_imei_ind (imei);
ALTER TABLE commands ADD INDEX com_imei_date_ind (imei, com_date);
USE irzserver4;
DROP PROCEDURE IF EXISTS clear_commands;
CREATE PROCEDURE clear_commands(IN days INT) BEGIN DELETE FROM commands WHERE ans_date < (UNIX_TIMESTAMP() - days * 24 * 60 * 60) * 1000; DELETE FROM commands WHERE queued < (UNIX_TIMESTAMP() - days * 24 * 60 * 60) * 1000; DELETE FROM commands WHERE com_date < (UNIX_TIMESTAMP() - days * 24 * 60 * 60) * 1000; END;
DROP PROCEDURE IF EXISTS clear_sessions;
CREATE PROCEDURE clear_sessions(IN days INT) BEGIN DELETE FROM sessions WHERE conndate < (UNIX_TIMESTAMP() - days * 24 * 60 * 60) * 1000; END;
SET GLOBAL event_scheduler = ON;
USE irzserver4;
CREATE EVENT IF NOT EXISTS clear_commands_event ON SCHEDULE EVERY 1 HOUR STARTS '2014-08-18 16:03:01' ON COMPLETION NOT PRESERVE ENABLE DO call clear_commands(7); 
CREATE EVENT IF NOT EXISTS clear_sessions_event ON SCHEDULE EVERY 1 HOUR STARTS '2014-08-18 16:03:01' ON COMPLETION NOT PRESERVE ENABLE DO call clear_sessions(7);
USE irzserver4;
INSERT IGNORE INTO commands_list (`id`,`command`,`comGroup`) VALUES (0,'',0);
INSERT IGNORE INTO commands_list (`id`,`command`,`comGroup`) VALUES (1,'$gp',1),(2,'$dcd',1),(3,'$dsr',1),(4,'$cts',1),(5,'$ri',1),(6,UNHEX('4002'),1),(7,UNHEX('4003'),1),(8,UNHEX('4006'),1),(9,UNHEX('4007'),1),(10,UNHEX('4008'),1),(11,UNHEX('4009'),1),(12,UNHEX('400A'),1),(13,UNHEX('400B'),1),(14,UNHEX('4001'),2),(15,UNHEX('4004'),2),(16,UNHEX('4005'),2),(17,'$ipr',3),(18,'$sim',3),(19,'$wait',3),(20,'$del c',1),(21, '$ussd', 4),(22, '$call', 5),(23, '$sms', 5),(24, '$frm', 5),(25, '$set', 5);